### ISSUE TITLE
IPhone 4 - ios 7.x bowser is always showing blackscreen only

### ISSUE THREAD

**Issue by shamun** [EricssonResearch/bowser#39]
Can anyone please fix the bowser to make it at-least work with openwebrtc or simplewebrtc or apprtc? Since day 1 i was not able to make Bowser ever work. Please see following screen shot:

Google Hangout - audio/video works perfectly
Talky - audio works perfectly.
With Bowser - nothing works

![20150327_144750](https://cloud.githubusercontent.com/assets/107349/6869008/b677561c-d490-11e4-883f-39d718224f28.jpg)

After execute of Bowser this is what my screen shows and then suddently while after it shows the previous screen.

![20150327_144815](https://cloud.githubusercontent.com/assets/107349/6869024/f6af663e-d490-11e4-817f-20f2f01ed451.jpg)

I am the saddest guy in the planet who tried every-time with Bowser and not yet seen it working.

**Comment by zevarito** [comment]
@shamun are you compiling your own or using appstore app?

The published app seem little outdated.

**Comment by shamun** [comment]
AppStore App i have tried and that is showing me every-time black screen. I have not tried the compiling yet.

**Comment by zevarito** [comment]
Same happen to me until I compiled it and add it a small patch to get
errors from the js console.

I am on mobile now but I could later show you how to do it, actually it is
a link to stackoverflow in some issue.

On Saturday, March 28, 2015, Shamun Toha <notifications@github.com> wrote:

> AppStore App i have tried and that is showing me every-time black screen.
> I have not tried the compiling yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EricssonResearch/bowser/issues/39#issuecomment-87188716>
> .
>


-- 
Sent from Gmail Mobile

**Comment by shamun** [comment]
OK  - please let me know the step by step. I have tried AppRTC long time ago in my OSX since then i never used anymore. If the instructions are well documented then i can regular do the testing of latest changes and keep tracking it.

**Comment by zevarito** [comment]
* Compile Openwebrtc with Cerbero (instructions on the wiki)
* git clone Bowser repo
* add your Openwebrtc compiled framework
* patch Bowser source with this guide:
http://stackoverflow.com/questions/6508313/javascript-console-log-in-an-ios-uiwebview
* compile and run


On Sat, Mar 28, 2015 at 11:34 AM, Shamun Toha <notifications@github.com>
wrote:

> OK - please let me know the step by step. I have tried AppRTC long time
> ago in my OSX since then i never used anymore. If the instructions are well
> documented then i can regular do the testing of latest changes and keep
> tracking it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EricssonResearch/bowser/issues/39#issuecomment-87236142>
> .
>



-- 
Alvaro

**Comment by shamun** [comment]
Compile OpenWebRTC with Cerero instructions on the wiki is removed? https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero

**Comment by zevarito** [comment]
That is because now it is the default way to compile:

https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

On Sat, Mar 28, 2015 at 11:44 AM, Shamun Toha <notifications@github.com>
wrote:

> Compile OpenWebRTC with Cerero instructions on the wiki is removed?
> https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EricssonResearch/bowser/issues/39#issuecomment-87238655>
> .
>



-- 
Alvaro

**Comment by shamun** [comment]
OK - let me try now and i will post here the updates. thank you

**Comment by shamun** [comment]
Its saying missing something when i apply bootstrap:

```
Suns-Air:cerbero sun$ ./cerbero-uninstalled bootstrap
WARNING: Using default configuration because /Users/sun/.cerbero/cerbero.cbc is missing
Traceback (most recent call last):
  File "./cerbero/utils/__init__.py", line 259, in parse_file
    execfile(filename, dict)
  File "/Users/sun/cerbero/config/darwin.config", line 87, in <module>
    raise Exception ("GL headers path not found: %s" % gl_headers)
Exception: GL headers path not found: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Headers
Configuration Error: Could not include config file (/Users/sun/cerbero/config/darwin.config)
```

**Comment by shamun** [comment]
Got error, was keep saying following:

```
Recipe 'libiconv' failed at the build step 'extract' 
```

Then, i applied following then its moving next

```
$ sudo git config --global user.email "you@example.com" 
$ sudo git config --global user.name "Your Name"
```

**Comment by zevarito** [comment]
You will hit many issues and expect hours of compiling :)

On Saturday, March 28, 2015, Shamun Toha <notifications@github.com> wrote:

> Got error, was keep saying following:
>
> Recipe 'libiconv' failed at the build step 'extract'
>
> Then, i applied following then its moving next
>
> $ sudo git config --global user.email "you@example.com <javascript:_e(%7B%7D,'cvml','you@example.com');>"
> $ sudo git config --global user.name "Your Name"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EricssonResearch/bowser/issues/39#issuecomment-87252010>
> .
>


-- 
Sent from Gmail Mobile

**Comment by shamun** [comment]
OK - but i will put a summary. So that anyone else like me can read this issue and solve it. 
:)

**Comment by zevarito** [comment]
Now thinking on IOS version you require, I am not sure it will work ok on
IOS 7, did you google if openwebrtc support it?

On Saturday, March 28, 2015, Shamun Toha <notifications@github.com> wrote:

> OK - but i will put a summary. So that anyone else like me can read this
> issue and solve it.
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EricssonResearch/bowser/issues/39#issuecomment-87254713>
> .
>


-- 
Sent from Gmail Mobile

**Comment by shamun** [comment]
Not sure about OpenWebRTC. But Google Hangout, Talky, AppRTC works so i believe OpenWebRTC has to work. Lets see how it goes its still compiling......

**Comment by zevarito** [comment]
Openwebrtc is the core of Bowser.
It might happen that the published Bowser app targets an openwebrtc build
that doesn't require IOS 8, I think the latest do.

I think the whole point of building Bowser yourself is to be able to debug
your own apps. Blank screens may be caused from several aspects even non
webrtc related ones.

That's my experience but I am just start playing a week ago.

On Saturday, March 28, 2015, Shamun Toha <notifications@github.com> wrote:

> Not sure about OpenWebRTC. But Google Hangout, Talky, AppRTC works so i
> believe OpenWebRTC has to work. Lets see how it goes its still
> compiling......
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EricssonResearch/bowser/issues/39#issuecomment-87255349>
> .
>


-- 
Sent from Gmail Mobile

**Comment by shamun** [comment]
Bootstrap worked: ./cerbero-uninstalled -c config/cross-ios-universal.cbc bootstrap
Do i also have to do again? ./cerbero-uninstalled -c config/cross-ios-universal.cbc package openwebrtc

? (i do not trust simulator/emulators, i always build straight to the device)

**Comment by zevarito** [comment]
The guide works perfect still you might end googling some specific issues
of your platform/env.

For now I just compiled armv7 and ran on real devices.

On Saturday, March 28, 2015, Shamun Toha <notifications@github.com> wrote:

> Bootstrap worked: ./cerbero-uninstalled -c config/cross-ios-universal.cbc
> bootstrap
> Do i also have to do again? ./cerbero-uninstalled -c
> config/cross-ios-universal.cbc package openwebrtc
>
> ? (i do not trust simulator/emulators, i always build straight to the
> device)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EricssonResearch/bowser/issues/39#issuecomment-87258098>
> .
>


-- 
Sent from Gmail Mobile

**Comment by stefanalund** [comment]
You can temporarily use this pre-compiled framework but it is not optimised which can be a bit problematic on an iPhone 4:

http://static.verkstad.net/OpenWebRTC.framework_old.zip

**Comment by shamun** [comment]
Took few hours at the end This failed:

```
./cerbero-uninstalled -c config/cross-ios-universal.cbc package openwebrtc
```

As below:


```
[(32/32) openwebrtc -> configure ]
Recipe 'openwebrtc' failed at the build step 'configure'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "./cerbero/build/recipe.py", line 266, in <lambda>
    setattr(cls, step, lambda self, name=step: step_func(self, name))
  File "./cerbero/build/recipe.py", line 411, in _do_step
    stepfunc()
  File "/Users/sun/cerbero/recipes/openwebrtc.recipe", line 162, in configure
    raise Exception(err_nobuild)
Exception: You need to build openwebrtc for the host darwin before you can cross-compile it for ios
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort
Recipe 'openwebrtc' failed at the build step 'configure'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "./cerbero/build/recipe.py", line 266, in <lambda>
    setattr(cls, step, lambda self, name=step: step_func(self, name))
  File "./cerbero/build/recipe.py", line 411, in _do_step
    stepfunc()
  File "/Users/sun/cerbero/recipes/openwebrtc.recipe", line 162, in configure
    raise Exception(err_nobuild)
Exception: You need to build openwebrtc for the host darwin before you can cross-compile it for ios
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort
Recipe 'openwebrtc' failed at the build step 'configure'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "./cerbero/build/recipe.py", line 266, in <lambda>
    setattr(cls, step, lambda self, name=step: step_func(self, name))
  File "./cerbero/build/recipe.py", line 411, in _do_step
    stepfunc()
  File "/Users/sun/cerbero/recipes/openwebrtc.recipe", line 162, in configure
    raise Exception(err_nobuild)
Exception: You need to build openwebrtc for the host darwin before you can cross-compile it for ios
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort

```

I will Try the ZIP file too (not tried that yet was waiting for the first one which failed).

**Comment by superdump** [comment]
Did you build for OS X first like the error message says?

**Comment by shamun** [comment]
YES 

./cerbero-uninstalled -c config/cross-ios-universal.cbc bootstrap (success)
and then
./cerbero-uninstalled -c config/cross-ios-universal.cbc package openwebrtc (failed)

**Comment by superdump** [comment]
Those are the commands to build for iOS. Try:

```
./cerbero-uninstalled -c config/osx-x86-64.cbc bootstrap
./cerbero-uninstalled -c config/osx-x86-64.cbc package openwebrtc
```

And then run the package command again for iOS.

**Comment by shamun** [comment]
Following was success:

./cerbero-uninstalled -c config/osx-x86-64.cbc bootstrap
./cerbero-uninstalled -c config/osx-x86-64.cbc package openwebrtc
./cerbero-uninstalled -c config/cross-ios-universal.cbc package openwebrtc
-----> Package successfully created in /Users/sun/cerbero/openwebrtc-devel-0.1.0-ios-universal.pkg

How can i now deploy this to iPhone 4 and check bowser?

**Comment by shamun** [comment]
Hello? What is next? how do i do the first hello world? (no documentation found , please provide well documentation or hints)

**Comment by superdump** [comment]
We still need to update Bowser to make use of the framework, though the changes are pretty minor build system changes in Xcode.

**Comment by shamun** [comment]
Having not use Bowser or with Bowser. 

How can a starter use the framework to make his hello world? Can you please share a documentation for that.

**Comment by superdump** [comment]
Here is information about how to add the framework to an Xcode project (choose the section depending on whether you're developing for OS X or iOS): https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC#using-the-results
Here is a slightly outdated iOS app guide:
https://github.com/EricssonResearch/openwebrtc-examples/wiki/Developing-iOS-apps

@stefanalund - do you have anything you want to add?
